CREATE DATABASE IF NOT EXISTS productsDB;

use productsDB;

CREATE TABLE product (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(400) NOT NULL,
  price DECIMAL,
  createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);